### ISSUE TITLE
I don't want anything for the "quote block". However I save and it automatically adds "| "         ¯\_(?)_/¯

### ISSUE THREAD

**Issue by ddileo** [fjl5/quoteme#1]
browser:latest Chrome
use: quote text for ChatGPT
![¡¡¡¡_2023-02-27_23-14](https://user-images.githubusercontent.com/6726154/221697993-ecfe3af6-cadf-406b-86ec-5418399edc8c.png)

**Comment by fjl5** [comment]
I can confirm this is a bug... The defaults for all three markers are only intended for new installs, but they get applied to each empty value. Nice catch, thank you! Hope to get a fix out soon.

**Comment by fjl5** [comment]
Fixed Version has been uploaded to both chrome web store and addons.mozilla.org.
